### ISSUE TITLE
Yelp API v2 is no longer accepting new signups

### ISSUE THREAD

**Issue by iancward** [jvarness/hubot-lunchtime#12]
It looks like Yelp is telling folks to sign up for Yelp Fusion: https://engineeringblog.yelp.com/2017/02/recent-improvements-to-the-fusion-api.html

Can this be updated to support the Yelp Fusion API instead?

**Comment by jvarness** [comment]
@iancward thank you for bringing this to my attention.

I need to investigate a little further before I can make a determination, but I think I'll be able to.

**Comment by jvarness** [comment]
@iancward I've determined what work needs to be done in order to consume this new API:

* The URL for searches has changed. Instead of `/v2/search` it's now `v3/businesses/search`. The parameters are luckily still the same, but the URL needs to be updated.
* Yelp API v2 uses the OAuth 1a spec, whereas Yelp Fusion requires OAuth 2. I'll need to revise the script and the dependencies to use OAuth 2. Since I've never worked with OAuth 2, I'll need to figure out what changes will be required for that, and as far as I can tell [oauth-signature](https://www.npmjs.com/package/oauth-signature) doesn't support OAuth 2.

I'm hoping that sometime this month I'll be able to complete this. No need to do anything on your part, I'm just letting you and others know that this might take some time.

**Comment by iancward** [comment]
Ok, cool thanks!

**Comment by jvarness** [comment]
Fixed with v0.2.0
